# Site settings
title: Thomas Gubler
email: thomas@thomasgubler.com
description: "Thomas Gubler"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: ffffff #18bc9c #80B3FF
  secondary: 000000 # 2c3e50 #FD6E8A
  secondary-dark: 00000 #233140 #A2122F

# Footer settings
footer:
  copyright: Thomas Gubler
  location: Winterthur, Switzerland
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  # - title: twitter
    # url: http://twitter.com/jekyllrb
  # - title: facebook
    # url:
  # - title: stack-overflow
    # url: http://stackoverflow.com/questions/tagged/jekyll
  # - title: bitbucket
    # url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/thomasgubler
  - title: linkedin
    url: https://www.linkedin.com/in/thomasgubler
  # - title: google-plus
  #   url: https://plus.google.com/+ThomasGubler


# Postal address (add as many lines as necessary)
address:
  # - line: 3481 Melrose Place
  # - line: Beverly Hills, CA 90210

# Credits content
credits: 'Freelance is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty
